# Generated by Django 4.2.4 on 2023-08-30 08:16

from django.db import migrations, models
import edoc_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=30)),
                ('surat', models.CharField(max_length=10)),
                ('klasifikasi', models.CharField(max_length=30)),
                ('katagori', models.CharField(max_length=30)),
                ('tgl', models.DateField()),
                ('no_surat', models.TextField(max_length=200)),
                ('kepada', models.CharField(max_length=200)),
                ('perihal', models.TextField(max_length=200)),
                ('upload_file', models.FileField(upload_to=edoc_app.models.user_folder)),
                ('today', models.DateField()),
            ],
            options={
                'db_table': 'DatabaseSurat',
            },
        ),
        migrations.CreateModel(
            name='JenisSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=30)),
                ('kode', models.TextField(max_length=10)),
                ('nama_jenis_surat', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'JenisSurat',
            },
        ),
        migrations.CreateModel(
            name='KlasifikasiSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=30)),
                ('kode', models.TextField(max_length=10)),
                ('nama_klasifikasi', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'KlasifikasiSurat',
            },
        ),
    ]
