# Generated by Django 4.2.4 on 2023-09-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoc_app', '0003_alter_kelompoksurat_id_alter_klasifikasisurat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('nama_Surat', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Surat',
            },
        ),
        migrations.RemoveField(
            model_name='kelompoksurat',
            name='kode',
        ),
        migrations.RemoveField(
            model_name='klasifikasisurat',
            name='kode',
        ),
    ]
