# Generated by Django 4.2.4 on 2023-09-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoc_app', '0007_databasesurat_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasesurat',
            name='id_user',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='databasesurat',
            name='perihal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kelompoksurat',
            name='id_user',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='klasifikasisurat',
            name='id_user',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='namasurat',
            name='id_user',
            field=models.CharField(max_length=4),
        ),
    ]
