# Generated by Django 4.2.4 on 2023-10-02 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edoc_app', '0008_alter_databasesurat_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasesurat',
            name='tahun',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
