# Generated by Django 4.2.4 on 2023-10-25 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edoc_app', '0010_kelompoksurat_username_klasifikasisurat_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompoksurat',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='klasifikasisurat',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
